# Generated by Django 4.2.2 on 2023-06-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="city",
            field=models.CharField(default="Noida", max_length=200),
            preserve_default=False,
        ),
    ]
